# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: The Feltor guide book
author: Matthias Wiesenberger
# logo: logo.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/mwiesenberger/xeus-cling-docu  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

only_build_toc_files: true
# Enable to use latex environment
parse:
    myst_enable_extensions: ["amsmath", "dollarmath"]
